version: "3.8"
services:
  free-tak-server-ui:
    image: freetakserver-ui:latest
    pull_policy: build
    build:
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - free-tak-ui-db:/home/freetak/data/
    environment:
      FTS_IP: 'free-tak-server'
      FTS_API_PORT: 19023
      FTS_API_PROTO: 'http'
      FTS_UI_EXPOSED_IP: 'free-tak-server-ui'
      FTS_MAP_EXPOSED_IP: 'free-tak-server-ui'
      FTS_MAP_PORT: 8000
      FTS_MAP_PROTO: 'http'
      FTS_UI_PORT: 5000
      FTS_UI_WSKEY: 'YourWebsocketKey'
      FTS_API_KEY: 'Bearer token'
      FTS_UI_SQLALCHEMY_DATABASE_URI: 'sqlite:////home/freetak/data/FTSServer-UI.db'

volumes:
  free-tak-ui-db: